/**
 * Bakes vendor logos into src/components/brand/logo-data.ts.
 *
 * Run with `npm run logos:fetch`. Output is committed, so the app has no
 * runtime icon dependency and no network call on render — the generated file
 * is the source of truth once written.
 *
 * Sources, in preference order, all open-licensed:
 *   logos:*         SVG Logos (CC0) — full-colour official marks
 *   devicon:*       Devicon (MIT) — full-colour, fills a few gaps
 *   simple-icons:*  Simple Icons (CC0) — official single-path silhouettes,
 *                   rendered in the brand's own hex
 *   mdi:* / cib:*   monochrome fallbacks where nothing else carries the brand
 *
 * The logos remain the trademarks of their owners. They are used here to
 * identify the products a client selects, which is what the form is for.
 */

import { writeFile } from "node:fs/promises";

/** catalog slug -> candidate Iconify names, best first. */
const SOURCES: Record<string, string[]> = {
  // Section 4 platforms and the headline vendors
  snowflake: ["logos:snowflake-icon", "logos:snowflake", "simple-icons:snowflake"],
  databricks: ["devicon:databricks", "simple-icons:databricks"],
  aws: ["logos:aws"],
  gcp: ["logos:google-cloud"],
  azure: ["logos:microsoft-azure", "logos:azure-icon"],

  // BI / reporting
  powerbi: ["logos:microsoft-power-bi"],
  tableau: ["logos:tableau-icon", "logos:tableau"],
  looker: ["logos:looker-icon", "logos:looker"],
  qlik: ["logos:qlik"],
  metabase: ["logos:metabase"],
  superset: ["logos:apache-superset-icon", "logos:apache-superset"],

  // Warehousing
  bigquery: ["devicon:googlecloud", "simple-icons:googlebigquery"],
  redshift: ["logos:aws-redshift"],
  sqlserver: ["devicon:microsoftsqlserver"],
  clickhouse: ["simple-icons:clickhouse"],
  teradata: ["simple-icons:teradata"],
  postgres: ["logos:postgresql"],
  mysql: ["logos:mysql-icon", "logos:mysql"],

  // Sources
  sap: ["logos:sap"],
  oracle: ["logos:oracle"],
  salesforce: ["logos:salesforce"],
  mongodb: ["logos:mongodb-icon", "logos:mongodb"],
  kafka: ["logos:kafka-icon", "logos:kafka"],
  hubspot: ["logos:hubspot"],
  shopify: ["logos:shopify"],
  stripe: ["logos:stripe"],
  dynamics: ["mdi:microsoft-dynamics-365"],
  netsuite: ["cib:oracle-netsuite"],
  workday: ["arcticons:workday"],
  excel: ["vscode-icons:file-type-excel", "devicon:microsoftsqlserver"],

  // Clouds
  ibmcloud: ["logos:ibm"],
  oraclecloud: ["logos:oracle"],

  /**
   * Microsoft Fabric and Azure Synapse have no logo in any open icon set —
   * checked Iconify (all sets), Simple Icons, and Wikimedia Commons. Both are
   * Microsoft products, so they carry the vendor's own corporate/Azure mark
   * rather than an invented monogram.
   */
  fabric: ["logos:microsoft"],
  synapse: ["logos:microsoft-azure"],
};

/**
 * Brand hex for monochrome sets, which ship a shape but no colour.
 *
 * These are painted on the white tile BrandMark uses, so each one has to stay
 * legible against white. ClickHouse is the one brand whose primary yellow does
 * not (1.51:1) — its own light-background treatment is black, with the yellow
 * reserved for dark grounds, so black is the faithful choice here rather than
 * a darkened yellow.
 */
const MONO_TINT: Record<string, string> = {
  databricks: "#FF3621",
  clickhouse: "#161616",
  teradata: "#F37440",
  bigquery: "#669DF6",
  dynamics: "#3FA9F5",
  netsuite: "#0086C9",
  workday: "#F38B00",
};

type Fetched = { body: string; width: number; height: number; tint?: string };

async function fetchIcon(name: string): Promise<Fetched | null> {
  const [prefix, icon] = name.split(":");
  const res = await fetch(
    `https://api.iconify.design/${prefix}.json?icons=${icon}`,
  );
  if (!res.ok) return null;

  const data = (await res.json()) as {
    icons?: Record<string, { body: string; width?: number; height?: number }>;
    width?: number;
    height?: number;
  };
  const entry = data.icons?.[icon!];
  if (!entry?.body) return null;

  return {
    body: entry.body,
    width: entry.width ?? data.width ?? 24,
    height: entry.height ?? data.height ?? 24,
  };
}

const resolved: Record<string, Fetched> = {};
const failed: string[] = [];

for (const [slug, candidates] of Object.entries(SOURCES)) {
  let hit: Fetched | null = null;
  let via = "";

  for (const candidate of candidates) {
    hit = await fetchIcon(candidate);
    if (hit) {
      via = candidate;
      break;
    }
  }

  if (!hit) {
    failed.push(slug);
    console.warn(`  ✗ ${slug.padEnd(12)} no source resolved`);
    continue;
  }

  if (MONO_TINT[slug]) hit.tint = MONO_TINT[slug];
  resolved[slug] = hit;
  console.log(
    `  ✓ ${slug.padEnd(12)} ${via.padEnd(32)} ${hit.width}×${hit.height}${hit.tint ? ` tint ${hit.tint}` : ""}`,
  );
}

const header = `// GENERATED by scripts/fetch-logos.mts — do not edit by hand.
// Run \`npm run logos:fetch\` to refresh.
//
// Vendor logos from open-licensed icon sets (SVG Logos CC0, Devicon MIT,
// Simple Icons CC0). Each remains the trademark of its owner and is used to
// identify the product a client is selecting.
//
// \`tint\` is set only for monochrome sources, where the path carries no colour
// of its own and BrandMark paints it in the brand's hex.

export type LogoData = {
  body: string;
  width: number;
  height: number;
  tint?: string;
};

export const LOGOS: Record<string, LogoData> = `;

await writeFile(
  new URL("../src/components/brand/logo-data.ts", import.meta.url),
  `${header}${JSON.stringify(resolved, null, 2)};\n`,
  "utf8",
);

console.log(
  `\nWrote ${Object.keys(resolved).length} logos.${failed.length ? ` Unresolved: ${failed.join(", ")}` : ""}`,
);
