"""Postgres access for the workers.

Two things about this schema are easy to get wrong from raw SQL, because Prisma
hides them from the TypeScript side:

  1. `@default(cuid())` and `@updatedAt` are generated by the Prisma *client*,
     not by Postgres. The columns carry no DEFAULT, so every insert from here
     must supply `id` and `updatedAt` itself. `new_id()` and `now()` exist for
     that, and omitting them fails at runtime rather than at import.

  2. Prisma does not snake_case column names, so identifiers are camelCase and
     have to be double-quoted in every statement.
"""

from __future__ import annotations

import datetime as dt
import os
import secrets
from collections.abc import Iterator
from contextlib import contextmanager
from typing import Any

import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

from .config import get_config

_pool: ConnectionPool | None = None


def new_id() -> str:
    """A collision-safe, roughly time-sortable id for a Prisma `String @id`.

    Prisma writes cuids; the column is plain TEXT and never parsed, so anything
    unique works. Leading the value with a base36 timestamp keeps rows in insert
    order under an index, which makes `ORDER BY id` a usable fallback.
    """
    ms = int(dt.datetime.now(dt.UTC).timestamp() * 1000)
    stamp = ""
    while ms:
        ms, r = divmod(ms, 36)
        stamp = "0123456789abcdefghijklmnopqrstuvwxyz"[r] + stamp
    return f"c{stamp}{secrets.token_hex(8)}"


def now() -> dt.datetime:
    return dt.datetime.now(dt.UTC)


def pool() -> ConnectionPool:
    global _pool
    if _pool is None:
        cfg = get_config()
        _pool = ConnectionPool(
            cfg.database_url,
            min_size=1,
            # A worker processes one job at a time; the headroom is for the
            # reaper and heartbeats running alongside a long handler.
            max_size=int(os.environ.get("DB_POOL_MAX", "4")),
            kwargs={"row_factory": dict_row, "autocommit": True},
            open=True,
        )
    return _pool


@contextmanager
def connection() -> Iterator[psycopg.Connection]:
    with pool().connection() as conn:
        yield conn


@contextmanager
def transaction() -> Iterator[psycopg.Connection]:
    """A unit of work that commits or rolls back as one.

    Each stage writes its output, marks its own job done, and enqueues the next
    stage inside one of these. That is what makes a crash safe: there is no
    window where work is persisted but the handoff is lost, or a job reads
    `done` while its rows are missing.
    """
    with pool().connection() as conn:
        with conn.transaction():
            yield conn


def query(conn: psycopg.Connection, sql: str, params: Any = None) -> list[dict[str, Any]]:
    with conn.cursor() as cur:
        cur.execute(sql, params)
        return cur.fetchall() if cur.description else []


def one(conn: psycopg.Connection, sql: str, params: Any = None) -> dict[str, Any] | None:
    rows = query(conn, sql, params)
    return rows[0] if rows else None


def execute(conn: psycopg.Connection, sql: str, params: Any = None) -> int:
    with conn.cursor() as cur:
        cur.execute(sql, params)
        return cur.rowcount


def close() -> None:
    global _pool
    if _pool is not None:
        _pool.close()
        _pool = None
